### ISSUE TITLE
Signing issues with latest version

### ISSUE THREAD

**Issue by IzzySoft** [maksim-m/Popular-Movies-App#14] opened 2017-11-01 13:24 UTC
On the APK from the latest release `apksigner` throws an error:

    ERROR: JAR signer CERT.RSA: JAR signature META-INF/CERT.SF indicates the APK is signed using APK Signature Scheme v2 but no such signature was found. Signature stripped?

This means two things: newer versions of fdroidserver (I have to upgrade mine soon as the version I run isn't supported by the latest Android clients) will reject the package – and devices running Nougat or above certainly will as well.

Could you please check and fix this? Thanks!

**Comment by IzzySoft** [comment] 2017-11-02 08:13
Update: As a couple of other projects had the same issues, I'd filed reports with them too. Two of them were able to solve it in a very easy way: Simply recompile the APK with a recent version of Android Studio.

* [CameraFilter](https://github.com/nekocode/CameraFilter/issues/15#issuecomment-341339598)
* [Bukanir](https://github.com/gen2brain/bukanir/issues/8#issuecomment-341268375)

Seems there was a bug in a previous version of it (probably when they started integrating v2-signing). So could you try that and let me know? Thanks in advance!

**Comment by maksim-m** [comment] 2017-11-05 11:25
I can't reproduce the issue. I get the following output from `apksigner` (build-tools 27.0.0): 
```
$ apksigner verify PopularMoviesApp-v2.1.apk
WARNING: META-INF/rxjava.properties not protected by signature. Unauthorized mod
ifications to this JAR entry will not be detected. Delete or move the entry outs
ide of META-INF/.
```
There is a warning, but the apk signature is valid. 

I rebuild the app with latest SDK and build tools, could you check [this apk](http://ge.tt/37TN4Dn2)? Is problem still persist?

**Comment by IzzySoft** [comment] 2017-11-05 12:39
Could it be you've replaced the APK on releases and there was a different one attached to v2.1 when it was released (timestamps differ: the one I had here had 2016-09-30, the current one has 2017-05-24)? I've just grabbed the one attached right now, and can confirm your results (so I replaced the copy I've got here with the current one).

I cannot check the link you just provided (some resources are blocked here, guess it's the URL shortener). If you can give me a direct link, I could check again – but if it verifies at your end with `apksigner`, that should suffice :wink:

With the current version verifying successfully, I'd consider the issue solved. So feel free to close it (or keep it open if you want to fix that warning as well and have the issue as reminder).

Thanks a lot!

**Comment by maksim-m** [comment] 2017-11-05 18:10
No, I did not replace or update the apk on releases page. Strange :hushed:

Anyway, the problem seems resolved, so I close the issue.

**Closed as completed by maksim-m** 2017-11-05 18:10 UTC

**Comment by IzzySoft** [comment] 2017-11-05 18:16
Very strange indeed – especially considering the different time-stamps of the file(s). As I only pick from here, you having replaced the attachment on (or after) 2017-05-24 was the easiest explanation. And the only one I could come up with.

Well, whatever it was, it's solved now luckily. No use to marter our brains (unless we need to to reproduce it in the future …)

Thanks again – and the best for the future of your project(s)!
